```{r}
library(tidyverse)
library(scales)
library(RColorBrewer)
library(arrow)

caption <- "Max Woolf — minimaxir.com"

sessionInfo()
```

```{r}
theme_set(theme_minimal(base_size = 8, base_family = "Overpass") +
  theme(
    plot.title = element_text(size = 8, face = "bold"),
    plot.subtitle = element_text(color = "#666666", size = 6),
    axis.title.x = element_text(size = 6),
    axis.title.y = element_text(size = 6),
    plot.caption = element_text(size = 5, color = "#969696"),
    plot.background = element_rect(fill = "#FFFFFF", color = "#FFFFFF"),
    legend.title = element_text(size = 8),
    # legend.key.width = unit(0.25, unit = "cm"),
    # panel.grid.minor = element_blank()
  ))
```


```{r}
df <- read_parquet("/Users/maxwoolf/Downloads/mtg_embeddings_2d.parquet")

df %>% head()
```

```{r}
color_identity <- function(color_sum, is_B, is_U, is_R, is_G, is_W) {
  if (color_sum == 0) {
    color <- "colorless"
  } else if (color_sum >= 2) {
    color <- "multicolor"
  } else if (is_B) {
    color <- "black"
  } else if (is_U) {
    color <- "blue"
  } else if (is_R) {
    color <- "red"
  } else if (is_G) {
    color <- "green"
  } else if (is_W) {
    color <- "white"
  }

  color
}


df_colors <- df %>%
  mutate(
    is_B = str_detect(manaCost, "B"),
    is_U = str_detect(manaCost, "U"),
    is_R = str_detect(manaCost, "R"),
    is_G = str_detect(manaCost, "G"),
    is_W = str_detect(manaCost, "W"),
    color_sum = is_B + is_U + is_R + is_G + is_W,
  ) %>%
  filter(!is.na(color_sum)) %>%
  rowwise() %>%
  mutate(
    color = color_identity(color_sum, is_B, is_U, is_R, is_G, is_W),
    color = factor(color, levels = c("white", "blue", "black", "red", "green", "multicolor", "colorless"))
  ) %>%
  ungroup() %>%
  select(name, x_2d, y_2d, color)

df_colors %>% head(10)
```

## 2D UMAP Projection

```{r}
colors_hex <- c(
  "white" = "#F9FAF4",
  "blue" = "#0E68AB",
  "black" = "#150B00",
  "red" = "#D3202A",
  "green" = "#00733E",
  "multicolor" = "#DAA520",
  "colorless" = "#C9C5C0"
)


plot <- ggplot(df_colors, aes(x = x_2d, y = y_2d, fill = color)) +
  geom_point(shape = 21, size = 0.5, stroke = 0.04, alpha = 0.7, color = "black") +
  scale_x_continuous(limits = c(NA, 426)) +
  scale_y_continuous(limits = c(-347, NA)) +
  scale_fill_manual(values = colors_hex) +
  guides(fill = guide_legend(
    override.aes = list(size = 2, alpha = 1, stroke = 0.8),
    theme = theme(legend.byrow = TRUE),
    nrow = 1
  )) +
  labs(
    title = "2D UMAP Projection of Magic: The Gathering Card Embeddings",
    subtitle = "All distinct cards up to Aetherdrift (2025-02-14). Outliers removed.",
    caption = caption
  ) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 5, margin = margin(c(0.05, 0.0, 0.0, 0.0), unit = "cm")),
    legend.key.width = unit(0.75, unit = "cm"),
    legend.key.height = unit(0.25, unit = "cm"),
    legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
  )

ggsave("mtg_umap.png", plot, width = 4, height = 4)
```
